export const speciesOptions = [
  { value: "human", label: "Human" },
  { value: "alien", label: "Alien" },
  { value: "humanoid", label: "Humanoid" },
  { value: "poopybutthole", label: "Poopybutthole" },
  { value: "mythological creature", label: "Mythological Creature" },
  { value: "disease", label: "Disease" },
  { value: "animal", label: "Animal" },
  { value: "cronenberg", label: "Cronenberg" },
  { value: "robot", label: "Robot" },
  { value: "unknown", label: "Unknown" },
];

export const genderOptions = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "genderless", label: "Genderless" },
  { value: "unknown", label: "Unknown" },
];

export const statusOptions = [
  { value: "alive", label: "Alive" },
  { value: "dead", label: "Dead" },
  { value: "unknown", label: "Unknown" },
];

export const locationsTypeOptions = [
  { value: "planet", label: "Planet" },
  { value: "cluster", label: "Cluster" },
  { value: "station", label: "Space Station" },
  { value: "tv", label: "TV" },
  { value: "resort", label: "Resort" },
  { value: "town", label: "Fantasy Town" },
  { value: "dream", label: "Dream" },
  { value: "menagerie", label: "Menagerie" },
  { value: "game", label: "Game" },
  { value: "customs", label: "Customs" },
  { value: "daycare", label: "Daycare" },
  { value: "dwarf planet", label: "Dwarf planet (Celestial Dwarf)" },
  { value: "miniverse", label: "Miniverse" },
  { value: "teenyverse", label: "Teenyverse" },
  { value: "box", label: "Box" },
  { value: "spacecraft", label: "Spacecraft" },
  {
    value: "artificially generated world",
    label: "Artificially Generated World",
  },
  { value: "machine", label: "Machine" },
  { value: "arcade", label: "Arcade" },
  { value: "spa", label: "Spa" },
  { value: "quadrant", label: "Quadrant" },
  { value: "quasar", label: "Quasar" },
  { value: "mount", label: "Mount" },
  { value: "liquid", label: "Liquid" },
  { value: "convention", label: "Convention" },
  { value: "woods", label: "Woods" },
  { value: "diegesis", label: "Diegesis" },
  {
    value: "non-diegetic alternative reality",
    label: "Non-Diegetic Alternative Reality",
  },
  { value: "nightmare", label: "Nightmare" },
  { value: "asteroid", label: "Asteroid" },
  { value: "acid plant", label: "Acid Plant" },
  { value: "dimension", label: "Dimension" },
  { value: "reality", label: "Reality" },
  { value: "death star", label: "Death Star" },
  { value: "spacecraft", label: "Spacecraft" },
  { value: "base", label: "Base" },
  { value: "elemental rings", label: "Elemental Rings" },
  { value: "human", label: "Human" },
  { value: "space", label: "Space" },
  { value: "hell", label: "Hell" },
  { value: "police department", label: "Police Department" },
  { value: "country", label: "Country" },
  { value: "consciousness", label: "Consciousness" },
  { value: "memory", label: "Memory" },
];

export const dimensionsOptions = [
  { value: "C-137", label: "Dimension C-137" },
  { value: "post-apocalyptic", label: "Post-Apocalyptic Dimension" },
  { value: "replacement", label: "Replacement Dimension" },
  { value: "cronenberg", label: "Cronenberg Dimension" },
  { value: "fantasy", label: "Fantasy Dimension" },
  { value: "5-126", label: "Dimension 5-126" },
  { value: "testicle", label: "Testicle Monster Dimension" },
  { value: "Cromulon", label: "Cromulon Dimension" },
  { value: "C-500A", label: "Dimension C-500A" },
  { value: "K-83", label: "Dimension K-83" },
  { value: "J19ζ7", label: "Dimension J19ζ7" },
  { value: "eric stoltz mask", label: "Eric Stoltz Mask Dimension" },
  {
    value: `evil Rick's target dimension`,
    label: `Evil Rick's Target Dimension`,
  },
  { value: "eric stoltz mask", label: "Eric Stoltz Mask Dimension" },
  {
    value: "giant telepathic spiders",
    label: "Giant Telepathic Spiders Dimension",
  },
  { value: "D-99", label: "Dimension D-99" },
  { value: "D716", label: "Dimension D716" },
  { value: "J-22", label: "Dimension J-22" },
  { value: "C-35", label: "Dimension C-35" },
  { value: "pizza", label: "Pizza Dimension" },
  { value: "phone", label: "Phone Dimension" },
  { value: "chair", label: "Chair Dimension" },
  { value: "fascist", label: "Fascist Dimension" },
  { value: "wasp", label: "Wasp Dimension" },
  { value: "tusk", label: "Tusk Dimension" },
  { value: "magic", label: "Magic Dimension" },
  { value: "merged", label: "Merged Dimension" },
  { value: "unknown", label: "Unknown" },
];
